run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - structcheck
    - deadcode
    - gofmt
    - goimports

issues:
  exclude-use-default: false
